-- Replace the first demo inventory with three fresh approved listings.
-- Public users see rounded public points plus approximate area visualization;
-- exact owner-drawn polygons stay private until approval or booking.

insert into public.legal_region_configs (
  country_code,
  country_name,
  country_slug,
  admin_area_code,
  admin_area_name,
  admin_area_slug,
  public_location_precision_meters,
  hunter_permit_required,
  firearm_notice,
  access_terms,
  min_booking_notice_days,
  seo_title,
  seo_description
)
values
  ('US', 'United States', 'united-states', 'GA', 'Georgia', 'georgia', 25000, true, 'Georgia hunting license, hunter education, private land permission, harvest reporting, and species rules may apply.', 'Private land access is granted only after landowner approval and signed access terms.', 5, 'Georgia hunting leases and private land access', 'Search Georgia hunting leases, private hunting land, hunting clubs, and landowner-approved access.'),
  ('US', 'United States', 'united-states', 'TX', 'Texas', 'texas', 30000, true, 'Texas hunting license, hunter education, species tags, public road rules, and county firearm rules may apply.', 'Respect landowner rules, game laws, county ordinances, and posted access windows.', 5, 'Texas hunting leases and private ranch access', 'Search Texas hunting leases, private ranch access, whitetail leases, mule deer leases, and seasonal hunting land.'),
  ('US', 'United States', 'united-states', 'MT', 'Montana', 'montana', 35000, true, 'Montana conservation license, hunting license, species tags, access rules, and private land permission may apply.', 'Access is conditional on landowner approval, route instructions, and seasonal restrictions.', 7, 'Montana hunting leases and ranch access', 'Explore Montana hunting leases, private ranch access, elk properties, and landowner-approved hunting opportunities.')
on conflict (country_code, admin_area_code) do update
set country_name = excluded.country_name,
    country_slug = excluded.country_slug,
    admin_area_name = excluded.admin_area_name,
    admin_area_slug = excluded.admin_area_slug,
    public_location_precision_meters = excluded.public_location_precision_meters,
    hunter_permit_required = excluded.hunter_permit_required,
    firearm_notice = excluded.firearm_notice,
    access_terms = excluded.access_terms,
    min_booking_notice_days = excluded.min_booking_notice_days,
    seo_title = excluded.seo_title,
    seo_description = excluded.seo_description,
    market_enabled = true;

insert into auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
)
values (
  '11111111-1111-4111-8111-111111111111',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'demo-landowner@huntfields.local',
  extensions.crypt('huntfields-demo-password', extensions.gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Huntfields Demo Landowner"}',
  now(),
  now()
)
on conflict (id) do update
set email = excluded.email,
    raw_user_meta_data = excluded.raw_user_meta_data,
    updated_at = now();

insert into public.profiles (id, role, full_name, country_code, onboarding_completed)
values (
  '11111111-1111-4111-8111-111111111111',
  'landowner',
  'Huntfields Demo Landowner',
  'US',
  true
)
on conflict (id) do update
set role = 'landowner',
    full_name = excluded.full_name,
    country_code = excluded.country_code,
    onboarding_completed = true;

delete from public.listings
where owner_id = '11111111-1111-4111-8111-111111111111'
  and slug in (
    'texas-hill-country-whitetail-season-lease',
    'colorado-gunnison-basin-elk-mule-deer-access',
    'montana-breaks-deer-antelope-guided-access',
    'georgia-flint-river-whitetail-turkey-lease',
    'texas-panhandle-mule-deer-quail-lease',
    'montana-bitterroot-elk-black-bear-access'
  );

insert into public.listings (
  id,
  owner_id,
  listing_type_id,
  status,
  title,
  slug,
  summary,
  description,
  country_code,
  country_name,
  admin_area_code,
  admin_area_name,
  region_name,
  region_slug,
  nearest_town,
  address_private,
  boundary_geojson,
  wildlife,
  amenities,
  rules,
  price_cents,
  currency,
  price_unit,
  cover_image_path,
  available_from,
  available_to,
  featured_score,
  published_at
)
values
  (
    '33333333-3333-4333-8333-333333333331',
    '11111111-1111-4111-8111-111111111111',
    (select id from public.listing_types where slug = 'season-lease'),
    'approved',
    'Georgia Flint River Whitetail and Turkey Lease',
    'georgia-flint-river-whitetail-turkey-lease',
    'A Southeast hunting lease with pine blocks, hardwood drains, food plots, and strong deer and turkey movement near Albany.',
    'This season lease is built for a small, vetted hunting party that wants a clearly defined private access area without exposing the exact boundary publicly. The owner-drawn polygon covers huntable pine, hardwood, creek-edge, and food plot sections. Gate codes, stand zones, and exact parcel coordinates are released only after approval and signed access terms.',
    'US',
    'United States',
    'GA',
    'Georgia',
    'Flint River',
    'united-states/georgia',
    'Albany',
    'Private timber access road shared after approval',
    '{"type":"Polygon","coordinates":[[[-84.438,31.685],[-84.372,31.697],[-84.358,31.632],[-84.426,31.618],[-84.438,31.685]]]}',
    array['whitetail deer', 'wild turkey', 'feral hogs'],
    array['food plots', 'hardwood drains', 'creek crossing', 'gated access'],
    array['check-in before entry', 'no guests without approval', 'harvest reporting required'],
    540000,
    'USD',
    'per_season',
    '/images/listings/georgia-flint-river-whitetail-turkey-lease.jpg',
    '2026-09-01',
    '2027-01-31',
    99,
    now()
  ),
  (
    '33333333-3333-4333-8333-333333333332',
    '11111111-1111-4111-8111-111111111111',
    (select id from public.listing_types where slug = 'exclusive-lease'),
    'approved',
    'Texas Panhandle Mule Deer and Quail Lease',
    'texas-panhandle-mule-deer-quail-lease',
    'An exclusive Panhandle ranch lease with broken grassland, draws, water, and strong mule deer, whitetail, and quail habitat near Canadian.',
    'A private ranch access lease for hunters who need real acreage, clear operating rules, and privacy-gated boundaries. The owner has drawn the exact huntable block, including draws, senderos, water, and upland cover. Public maps show only an approximate area until the landowner approves the party and the access terms are signed.',
    'US',
    'United States',
    'TX',
    'Texas',
    'Texas Panhandle',
    'united-states/texas',
    'Canadian',
    'Ranch entrance shared after approval',
    '{"type":"Polygon","coordinates":[[[-100.475,35.935],[-100.381,35.942],[-100.365,35.873],[-100.459,35.859],[-100.475,35.935]]]}',
    array['mule deer', 'whitetail deer', 'bobwhite quail', 'feral hogs'],
    array['water', 'senderos', 'ranch roads', 'blind locations'],
    array['use marked ranch roads only', 'no night hunting', 'all guests must be approved'],
    980000,
    'USD',
    'per_season',
    '/images/listings/texas-panhandle-mule-deer-quail-lease.jpg',
    '2026-09-15',
    '2027-01-15',
    96,
    now()
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    '11111111-1111-4111-8111-111111111111',
    (select id from public.listing_types where slug = 'guided-hunt'),
    'approved',
    'Montana Bitterroot Elk and Black Bear Access',
    'montana-bitterroot-elk-black-bear-access',
    'A mountain access package in the Bitterroot with timber benches, meadow edges, glassing points, and guided support near Hamilton.',
    'This guided access listing gives hunters a realistic sense of terrain and scale before they request access, while keeping the exact owner-drawn route and boundary private. The defined huntable area includes timber, benches, meadow edges, and controlled approach routes. Final coordinates, gate instructions, and guide contact details are released after approval and signature.',
    'US',
    'United States',
    'MT',
    'Montana',
    'Bitterroot Valley',
    'united-states/montana',
    'Hamilton',
    'Private mountain access point shared after approval',
    '{"type":"Polygon","coordinates":[[[-114.305,46.347],[-114.211,46.359],[-114.196,46.285],[-114.292,46.273],[-114.305,46.347]]]}',
    array['elk', 'mule deer', 'black bear'],
    array['guided support', 'glassing points', 'seasonal two-track access', 'camp staging area'],
    array['guide orientation required', 'no off-route driving', 'pack out all trash'],
    680000,
    'USD',
    'per_week',
    '/images/listings/montana-bitterroot-elk-black-bear-access.jpg',
    '2026-09-01',
    '2026-11-30',
    93,
    now()
  )
on conflict (slug) do update
set title = excluded.title,
    summary = excluded.summary,
    description = excluded.description,
    owner_id = excluded.owner_id,
    listing_type_id = excluded.listing_type_id,
    status = 'approved',
    country_code = excluded.country_code,
    country_name = excluded.country_name,
    admin_area_code = excluded.admin_area_code,
    admin_area_name = excluded.admin_area_name,
    region_name = excluded.region_name,
    region_slug = excluded.region_slug,
    nearest_town = excluded.nearest_town,
    address_private = excluded.address_private,
    boundary_geojson = excluded.boundary_geojson,
    wildlife = excluded.wildlife,
    amenities = excluded.amenities,
    rules = excluded.rules,
    price_cents = excluded.price_cents,
    currency = excluded.currency,
    price_unit = excluded.price_unit,
    cover_image_path = excluded.cover_image_path,
    available_from = excluded.available_from,
    available_to = excluded.available_to,
    featured_score = excluded.featured_score,
    published_at = now();

insert into public.listing_compliance_profiles (
  listing_id,
  state_code,
  landowner_has_authority,
  hunting_lease_license_required,
  hunting_lease_license_number,
  insurance_required,
  insurance_summary,
  allowed_species,
  allowed_methods,
  prohibited_methods,
  guest_policy,
  vehicle_policy,
  alcohol_policy,
  emergency_contact_name,
  emergency_contact_phone,
  state_specific_answers
)
values
  (
    '33333333-3333-4333-8333-333333333331',
    'GA',
    true,
    false,
    null,
    true,
    'Signed access agreement and liability waiver required before exact access details are released.',
    array['whitetail deer', 'wild turkey', 'feral hogs'],
    array['rifle', 'archery', 'shotgun'],
    array['unapproved baiting', 'unapproved guests', 'entry outside approved windows'],
    'Approved hunting party only; no additional guests without written approval.',
    'Use designated timber roads and park only in approved areas.',
    'No alcohol while hunting or handling firearms.',
    'Property manager',
    '+1 229 555 0184',
    '{"demo": true, "public_area": "approximate"}'
  ),
  (
    '33333333-3333-4333-8333-333333333332',
    'TX',
    true,
    true,
    'TX-DEMO-LEASE-7310',
    true,
    'Landowner requires signed waiver and proof of personal hunting liability coverage where available.',
    array['mule deer', 'whitetail deer', 'bobwhite quail', 'feral hogs'],
    array['rifle', 'archery', 'shotgun'],
    array['night hunting', 'off-road travel after rain', 'additional vehicles without approval'],
    'Maximum approved party only; every hunter must be named before arrival.',
    'Use marked ranch roads only; closures apply during wet conditions.',
    'No alcohol while hunting, driving ranch roads, or handling firearms.',
    'Ranch manager',
    '+1 806 555 0138',
    '{"demo": true, "public_area": "approximate"}'
  ),
  (
    '33333333-3333-4333-8333-333333333333',
    'MT',
    true,
    false,
    null,
    true,
    'Guided access includes orientation, signed route rules, and liability waiver.',
    array['elk', 'mule deer', 'black bear'],
    array['rifle', 'archery'],
    array['off-route vehicle travel', 'unapproved campfires', 'shooting near livestock'],
    'Guide confirms party size and hunter details before access instructions are released.',
    'Seasonal access only; high-clearance vehicle recommended where permitted.',
    'No alcohol while hunting or driving access roads.',
    'Guide contact',
    '+1 406 555 0169',
    '{"demo": true, "public_area": "approximate"}'
  )
on conflict (listing_id) do update
set state_code = excluded.state_code,
    landowner_has_authority = excluded.landowner_has_authority,
    hunting_lease_license_required = excluded.hunting_lease_license_required,
    hunting_lease_license_number = excluded.hunting_lease_license_number,
    insurance_required = excluded.insurance_required,
    insurance_summary = excluded.insurance_summary,
    allowed_species = excluded.allowed_species,
    allowed_methods = excluded.allowed_methods,
    prohibited_methods = excluded.prohibited_methods,
    guest_policy = excluded.guest_policy,
    vehicle_policy = excluded.vehicle_policy,
    alcohol_policy = excluded.alcohol_policy,
    emergency_contact_name = excluded.emergency_contact_name,
    emergency_contact_phone = excluded.emergency_contact_phone,
    state_specific_answers = excluded.state_specific_answers;
